{% set name = "numpngw" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/numpngw-{{ version }}.tar.gz
  sha256: 54db993fd8d6ad3a96838a860224656b3d691b7692bd050e8ac145b2fbc89a8e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.6.0

test:
  imports:
    - numpngw
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/WarrenWeckesser/numpngw
  summary: Write numpy array(s) to a PNG or animated PNG file.
  license: BSD-2-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
